export const REDUX_KEY = 'PRODUCTS';
export const TAKELIST = 'TAKELIST';
export const TAKELISTSUCCESS = 'TAKELISTSUCCESS';

export const ADDPRODUCTS = 'ADDPRODUCTS';

export const ADDPRODUCTSSUCCESS = 'ADDPRODUCTSSUCCESS';


export const EDITPRODUCTS = 'EDITPRODUCTS';

export const EDITPRODUCTSSUCCESS = 'EDITPRODUCTSSUCCESS';

export const ERRORREQUEST = 'ERRORREQUEST';

export const DELETE = 'DELETE';

export const DELETESUCCESS = 'DELETESUCCESS';
