export const REDUX_KEY = 'HomePage';
export const TAKELISTACCOUNT = 'TAKELISTACCOUNT';
export const TAKELISTSUCCESSACCOUNT = 'TAKELISTSUCCESSACCOUNT';

export const ADDACCOUNT = 'ADDACCOUNT';

export const ADDACCOUNTSUCCESS = 'ADDACCOUNTSUCCESS';

export const TAKEROLEGROUP = 'TAKEROLEGROUP';

export const TAKEROLEGROUPSUCCESS = 'TAKEROLEGROUPSUCCESS';

export const EDITACCOUNT = 'EDITACCOUNT';

export const EDITACCOUNTSUCCESS = 'EDITACCOUNTSUCCESS';

export const ERRORREQUEST = 'ERRORREQUEST';

export const DELETE = 'DELETE';

export const DELETESUCCESS = 'DELETESUCCESS';
